//
// Copyright (c) 2022 INRIA
//
/** \file */

#ifndef PROXSUITE_OSQP_SPARSE_PRECOND_IDENTITY_HPP
#define PROXSUITE_OSQP_SPARSE_PRECOND_IDENTITY_HPP


#endif /* end of include guard PROXSUITE_OSQP_SPARSE_PRECOND_IDENTITY_HPP */
